
FROM ubuntu:16.04
MAINTAINER Alin Jurj <office@perfectweb.ro>

RUN apt-get update -qq
RUN apt-get install -qqy libcurl4-openssl-dev git make automake gcc g++ libssl-dev pkg-config libtool autoconf libcurl3-gnutls
